# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a15e4ecaf22b9acab1d93eb2c809c625384cab1fdb981e3a6c38466db252a3d9e002a17859c29081b98c7616faf8608ae4139f409118edc9bcaab4e62d62275

test:
  secret_key_base: e230f9c2d03f38363d11dc86efc5e6d262fef5a79da2291bb822d75fe7f2dd00647281661beedd45f501f6f56b5250ba978e48816c8649bb952c623ecc245cc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
